### ISSUE TITLE
Milestone 1.0 features to freeze

### ISSUE THREAD

**Issue by gaow** [stephenslab/mashr#58]
## Recent changes to the package

As previously discussed offline, here I summarize changes made since summer for consideration of a cran release:

1. Linear transformation for posterior (for common baseline application), changes to both `mash` call and functions to compute posterior matrices: [1](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/mash.R#L44), [2](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/mash.R#L209)
2. C++ implementation of the above, no interface changes.
3. A method to estimate null correlation; and consequenty changes to the original `estimate_null_correlation` function: [1](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/est_cor.R#L79), [2](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/est_cor.R#L15).
4. Function `mash_update_data` to update mash data (for common baseline, and for re-estimated V): [1](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/set_data.R#L83)
5. Sampling from posterior (R implementation only): [1](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/mash.R#L45)
6. Estimate of sharing based on posterior samples: [1](https://github.com/stephenslab/mashr/blob/f649010173efa34ed69ce0bd40a2f4f9cdcb28a6/R/get_functions.R#L163)

I've included links to those interfaces.  Hope it helps @pcarbo to review.

## Our current thoughts

We (@zouyuxin and I) are okay with all except:

- [ ] We prefer make `estimate_null_correlation` a private function for now for cran version.
- [ ] Not sure about the `seed` option in 5 above. Should we keep it with a default, or relying on users setting it beforehand via `set.seed`

## Next steps

- [ ] Review all documentation, including #49

**Comment by pcarbo** [comment]
That all sounds fine to me. (I have no strong opinions here.)

> Not sure about the seed option in 5 above.

@gaow I think this is okay as long as there is an option to not set the seed (e.g., with `seed = NULL`).

@gaow Maybe you can attempt to tackle Issue #49, and after that I will review documentation & vignettes?

**Comment by gaow** [comment]
@pcarbo sounds good. I do want to make some changes to posterior output object anyways (though the relevant get-functions should remain same interface which is the point).
